# Generated by Django 3.1 on 2021-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.TextField(),
        ),
    ]
