# Generated by Django 3.1 on 2021-03-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210308_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_post',
            new_name='title',
        ),
    ]
