# Generated by Django 3.1 on 2021-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categorykg_commentkg_postimagekg_postkg_posttagkg_postvideokg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentkg',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='postimagekg',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='postkg',
            name='category',
        ),
        migrations.RemoveField(
            model_name='posttagkg',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='postvideokg',
            name='post_video',
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('RU', 'RU'), ('KG', 'KG')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryKG',
        ),
        migrations.DeleteModel(
            name='CommentKG',
        ),
        migrations.DeleteModel(
            name='PostImageKG',
        ),
        migrations.DeleteModel(
            name='PostKG',
        ),
        migrations.DeleteModel(
            name='PostTagKG',
        ),
        migrations.DeleteModel(
            name='PostVideoKG',
        ),
    ]
