# Generated by Django 3.1 on 2021-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210308_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('RU', 'RU'), ('KG', 'KG')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
